[2025-01-30T19:35:39.347+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T19:35:39.354+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:34:42-07:00 [queued]>
[2025-01-30T19:35:39.359+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:34:42-07:00 [queued]>
[2025-01-30T19:35:39.360+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T19:35:39.365+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_raw_books> on 2025-01-30 19:34:42+00:00
[2025-01-30T19:35:39.368+0000] {standard_task_runner.py:72} INFO - Started process 193 to run task
[2025-01-30T19:35:39.370+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'collect_raw_books', 'manual__2025-01-30T12:34:42-07:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpt4hwh3x6']
[2025-01-30T19:35:39.371+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask collect_raw_books
[2025-01-30T19:35:39.392+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:34:42-07:00 [running]> on host 48308722451a
[2025-01-30T19:35:39.429+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='collect_raw_books' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T19:34:42+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T12:34:42-07:00'
[2025-01-30T19:35:39.430+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T19:35:39.436+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-30T19:35:39.436+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data_collection/collect_books.py --data_lake_path $DATA_LAKE_PATH --open_library_ids $OPEN_LIBRARY_IDS --execution_date $EXECUTION_DATE']
[2025-01-30T19:35:39.440+0000] {subprocess.py:99} INFO - Output:
[2025-01-30T19:35:44.701+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/.json
[2025-01-30T19:35:44.704+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.708+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/'}
[2025-01-30T19:35:44.708+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_
[2025-01-30T19:35:44.709+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL24503655M".json
[2025-01-30T19:35:44.709+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.709+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL24503655M"'}
[2025-01-30T19:35:44.710+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL24503655M"
[2025-01-30T19:35:44.710+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL47317227M".json
[2025-01-30T19:35:44.710+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.711+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL47317227M"'}
[2025-01-30T19:35:44.711+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL47317227M"
[2025-01-30T19:35:44.712+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL37985553M".json
[2025-01-30T19:35:44.712+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.712+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL37985553M"'}
[2025-01-30T19:35:44.712+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL37985553M"
[2025-01-30T19:35:44.713+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL8759604M".json
[2025-01-30T19:35:44.713+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.713+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL8759604M"'}
[2025-01-30T19:35:44.714+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL8759604M"
[2025-01-30T19:35:44.716+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL46057997M".json
[2025-01-30T19:35:44.717+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.718+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL46057997M"'}
[2025-01-30T19:35:44.719+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL46057997M"
[2025-01-30T19:35:44.719+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL23338573M".json
[2025-01-30T19:35:44.719+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.719+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL23338573M"'}
[2025-01-30T19:35:44.720+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL23338573M"
[2025-01-30T19:35:44.721+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL26974419M".json
[2025-01-30T19:35:44.722+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.723+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL26974419M"'}
[2025-01-30T19:35:44.723+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL26974419M"
[2025-01-30T19:35:44.723+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL33899062M".json
[2025-01-30T19:35:44.723+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.724+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL33899062M"'}
[2025-01-30T19:35:44.725+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL33899062M"
[2025-01-30T19:35:44.725+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL5204176M".json
[2025-01-30T19:35:44.726+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.727+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL5204176M"'}
[2025-01-30T19:35:44.727+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL5204176M"
[2025-01-30T19:35:44.728+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL38631342M".json
[2025-01-30T19:35:44.729+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:35:44.729+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL38631342M"'}
[2025-01-30T19:35:44.730+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL38631342M"
[2025-01-30T19:35:44.766+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-30T19:35:44.780+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T19:35:44.781+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=collect_raw_books, run_id=manual__2025-01-30T12:34:42-07:00, execution_date=20250130T193442, start_date=20250130T193539, end_date=20250130T193544
[2025-01-30T19:35:44.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T19:35:44.841+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T19:35:44.842+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
